name: smoke-test

on:
  push:
    branches: [ "master", "feature/**", "bugfix/**", "release/**" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
      
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Tag commit
      uses: hole19/git-tag-action@master
      env:
        TAG: "${{ env.GitVersion_FullSemVer }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
